name: Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          cd classroom
          npm install --legacy-peer-deps

      - name: Grant Execute Permission for Gradlew
        run: chmod +x classroom/android/gradlew

      - name: Build Android Release
        run: |
          cd classroom/android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: classroom/android/app/build/outputs/apk/release/app-release.apk
